VERSION: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    environment:
      - DB_HOST = localhost
      - DB_PORT = 3000
      - DB_USERNAME = root
      - DB_PASSWORD = Kumagoro1
      - DB_DATABASE = u-know
    ports:
      - "3306:3306"
    depends_on:
      - database
    networks:
      - nestjs_network

  database:
    image: mysql
    ports:
      -'3306:3306'
    volumes:
      - './mysql-backup:/data/db'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge